apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-deployment
  namespace: shop
  labels:
    app: shoppingcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
      - name: imran-shoppingcart
        image: siddhi/spring-boot:imran
        ports:
        - containerPort: 8080

